### ISSUE TITLE
[Phase 1] Backend load testing plan

### ISSUE THREAD

**Issue by DonAlexandro** [Imabulary/Imabulary#75]
## Problem
**As a** backend developer
**I want to** know what peak loads the system can withstand
**So that** I can find weak parts of the system and fix them before they go to production

**Comment by AndreyQA519** [comment]
First draft of document (highlighted red in the document). Need to discus with @DonAlexandro and @vladyslav-panchenko280
[ImabularyLoadTestPlan.pdf](https://github.com/user-attachments/files/15991879/ImabularyLoadTestPlan.pdf)
